### ISSUE TITLE
GCP DNS opt-in setup

### ISSUE THREAD

**Issue by evghen1** [web-seven/configuration-magento2-gcp#5]
## Issue summary:
As opt-in option we could make this configuration to manage DNS records, what allow setup Magento environments without external setup, if user set GCP as nameserver.
## Issue details:
Required to allow by XRD switcher to create GCP DNS record based on hostname from ingress value.
## Todo:
- [ ] Update XRD and Composition with optional creation of GCP DNS record equal to hostname of Magento ingress.
## Acceptance criteria:
- After deploy magento instance with activated DNS record creation, user shall be able immediately access Magento frontend by provided hostname. (in case if domain provider looks to GCP nameserver)

**Comment by evghen1** [comment]
@ca7alindev Any news?

**Comment by ca7alindev** [comment]
@evghen1, already done with creation of DNS in cloud, but still need a solution on how to create it optionally
